version: 2
updates:
  -
    package-ecosystem: npm
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: weekly
      day: wednesday
    commit-message:
      prefix: chore
    pull-request-branch-name:
      separator: "-"
    assignees:
      - hugo-t-b
  -
    package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    pull-request-branch-name:
      separator: "-"
    assignees:
      - hugo-t-b
