env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  accessor-pairs: error
  array-bracket-newline:
    - error
    -
      minItems: 1
      multiline: false
  array-bracket-spacing:
    - error
    - always
  array-callback-return: error
  array-element-newline: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  block-spacing: error
  brace-style: error
  camelcase: error
  class-methods-use-this: error
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-return: error
  curly: error
  default-case-last: error
  default-param-last: error
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-names:
    - error
    - never
  func-style: error
  function-call-argument-newline:
    - error
    - consistent
  generator-star-spacing:
    - error
    -
      before: false
      after: true
  grouped-accessor-pairs:
    - error
    - getBeforeSet
  guard-for-in: error
  implicit-arrow-linebreak: error
  indent:
    - error
    - 2
  init-declarations: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  lines-between-class-members:
    - error
    - always
    -
      exceptAfterSingleLine: true
  multiline-ternary:
    - error
    - always-multiline
  new-cap: error
  new-parens: error
  newline-per-chained-call: error
  no-array-constructor: error
  no-bitwise: error
  no-confusing-arrow:
    - error
    -
      onlyOneSimpleParam: true
  no-constructor-return: error
  no-duplicate-imports: error
  no-else-return:
    - error
    -
      allowElseIf: false
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-invalid-this: error
  no-label-var: error
  no-lonely-if: error
  no-magic-numbers:
    - error
    -
      ignoreDefaultValues: true
  no-mixed-operators: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines:
    - error
    -
      max: 1
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-promise-executor-return: error
  no-return-assign: error
  no-return-await: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-expressions: error
  no-unused-private-class-members: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-whitespace-before-property: error
  object-curly-newline:
    - error
    -
      ExportDeclaration:
        multiline: true
      ImportDeclaration: never
      ObjectExpression:
        minProperties: 1
      ObjectPattern: never
  object-curly-spacing:
    - error
    - always
  object-property-newline: error
  object-shorthand:
    - error
    - always
    -
      avoidExplicitReturnArrows: true
  one-var:
    - error
    - never
  operator-assignment: error
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props:
    - error
    - as-needed
  quotes: error
  require-atomic-updates: error
  require-await: error
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  semi-style: error
  sort-keys: error
  space-before-function-paren:
    - error
    -
      anonymous: always
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  strict: error
  switch-colon-spacing: error
  template-curly-spacing: error
  template-tag-spacing: error
  yield-star-spacing: error
  yoda: error
