root: true
extends: "@hugo-t-b/eslint-config/typescript"
ignorePatterns:
  - coverage
  - dist
  - "*.cjs"
settings:
  import/core-modules:
    - vite-node/client
    - vite-node/server
rules:
  "@typescript-eslint/no-floating-promises": off
