name: CI
on:
  - push
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
      -
        name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      -
        name: Install dependencies
        run: pnpm install
      -
        name: Run eslint
        run: pnpm lint
  vitest:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
      -
        name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      -
        name: Install dependencies
        run: pnpm install
      -
        name: Run vitest
        run: pnpm test
