name: Publish
on:
  workflow_dispatch:
  release:
    types:
      - created
jobs:
  npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      -
        name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      -
        name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: "pnpm"
      -
        name: Install dependencies
        run: pnpm install
      -
        name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
